version: "3"

services:
  postgres15:
    image: postgres:15
    restart: unless-stopped
    env_file:
      - postgres.enc.env
    ports:
      - "5433:5432"
    volumes:
      - postgres15:/var/lib/postgresql/data
    networks:
      - postgresnet

  postgres14:
    image: postgres:14
    restart: unless-stopped
    env_file:
      - postgres.enc.env
    ports:
      - "5432:5432"
    volumes:
      - postgres14:/var/lib/postgresql/data
    networks:
      - postgresnet

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    environment:
      - "PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=False"
    env_file:
      - pgadmin.enc.env
    networks:
      - traefiknet
      - postgresnet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.bdeak.net`)"

volumes:
  postgres15:
  postgres14:

networks:
  traefiknet:
    external: true
  postgresnet:
    external: true
