version: "3"

services:
  stack-management:
    image: ghcr.io/bdeak4/stack-management:latest
    container_name: stack-management
    restart: unless-stopped
    env_file:
      - stack-management.enc.env
    networks:
      - traefiknet
      - postgresnet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stack-management.rule=Host(`stack.management`)"

networks:
  traefiknet:
    external: true
  postgresnet:
    external: true
